/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InvestionnaireDiploma } from './InvestionnaireDiploma.js';
export * as factories from './factories/index.js';
export { InvestionnaireDiploma__factory } from './factories/InvestionnaireDiploma__factory.js';